Models/ErrorViewModel.cs
using System;

namespace cadastro_cliente_mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pessoa.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace cadastro_cliente_mvc.Models
{
    public class Pessoa
    {
        [Display(Name = "id")]
        public int pessoaId { get; set; }

        [Display(Name = "Tipo")]
        public String tipoPessoa { get; set; }
        public String CPF { get; set; }

        [Display(Name = "Data de Nascimento")]
        public DateTime? DataNascimento { get; set; }
        public String Nome { get; set; }
        public String Sobrenome { get; set; }
        public String CNPJ { get; set; }

        [Display(Name = "Razão Social")]
        public String RazaoSocial { get; set; }

        [Display(Name = "Nome Fantasia")]
        public String NomeFantasia { get; set; }
        public String CEP { get; set; }
        public String Logradouro { get; set; }
        public int Numero { get; set; }
        public String Completemento { get; set; }
        public String Bairro { get; set; }
        public String Cidade { get; set; }
        public String UF { get; set; }
    }
}

Models/PessoaContexto.cs
using Microsoft.EntityFrameworkCore;

namespace cadastro_cliente_mvc.Models
{
    public class PessoaContexto : DbContext
    {
        public PessoaContexto(DbContextOptions<PessoaContexto> options) : base(options)
        {
        }
        public DbSet<Pessoa> Pessoa { get; set; }
    }
}

Models/TipoPessoa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cadastro_cliente_mvc.Models
{
    public class TipoPessoa
    {
        public string tipoPessoa { get; set; }
        public string Nome { get; set; }
    }
}

Controllers/HomeController.cs
using cadastro_cliente_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace cadastro_cliente_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using cadastro_cliente_mvc.Models;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace cadastro_cliente_mvc.Controllers
{
    public class PessoaController : Controller
    {
        private readonly ILogger<PessoaController> _logger;
        private readonly PessoaContexto _pessoaContext;

        public PessoaController(PessoaContexto pessoaContext, ILogger<PessoaController> logger)
        {
            _pessoaContext = pessoaContext;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(_pessoaContext.Pessoa.OrderBy(x => x.pessoaId).ToList());
        }
        public ActionResult Add()
        {            
            ViewBag.tipos = new List<TipoPessoa> {
                new TipoPessoa {tipoPessoa = "F", Nome="Física" },
                new TipoPessoa {tipoPessoa = "J", Nome="Jurídica" }
            };

            return View();
        }

        [HttpPost]
        public ActionResult Add(Pessoa pessoa)
        {
            _pessoaContext.Pessoa.Add(pessoa);
            _pessoaContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int Id)
        {
            var pessoa = _pessoaContext.Pessoa.Where(x => x.pessoaId == Id).FirstOrDefault();

            return View(pessoa);
        }

        [HttpPost]
        public ActionResult Delete(Pessoa pessoa)
        {
            _pessoaContext.Pessoa.Remove(pessoa);
            _pessoaContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int Id)
        {

            ViewBag.tipos = new List<TipoPessoa> {
                new TipoPessoa {tipoPessoa = "F", Nome="Física" },
                new TipoPessoa {tipoPessoa = "J", Nome="Jurídica" }
            };

            var pessoa = _pessoaContext.Pessoa.Where(x => x.pessoaId == Id).FirstOrDefault();

            return View(pessoa);
        }
        public ActionResult Details(int Id)
        {
            var pessoa = _pessoaContext.Pessoa.Where(x => x.pessoaId == Id).FirstOrDefault();

            return View(pessoa);
        }

        [HttpPost]
        public ActionResult Edit(Pessoa pessoa)
        {
            if (pessoa.tipoPessoa == "F")
            {
                pessoa.CNPJ = "";
                pessoa.RazaoSocial = "";
                pessoa.NomeFantasia = "";
            }
            else
            {
                pessoa.CPF = "";
                pessoa.DataNascimento = null;
                pessoa.Nome = "";
                pessoa.Sobrenome = "";
            }


            _pessoaContext.Entry(pessoa).State = EntityState.Modified;            
            _pessoaContext.SaveChanges();
            return RedirectToAction("Index");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Principal";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo ao Cadastro de Cliente!</h1>
</div>

Views/Pessoa/Add.cshtml
@model cadastro_cliente_mvc.Models.Pessoa
@{
    ViewData["Title"] = "Adicionar Pessoa";
}

<h2>Adicionar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Pessoa</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("pessoaId", 0)

    <div class="form-group">
        <b>@Html.LabelFor(model => model.tipoPessoa, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.tipoPessoa, ((IEnumerable<TipoPessoa>)ViewBag.tipos).Select(option => new SelectListItem
           {
               Text = option.Nome,
               Value = option.tipoPessoa,
               Selected = (Model != null) && (option.tipoPessoa == Model.tipoPessoa)
           }), new { @id = "tipoPessoa", @class = "form-control" })
        </div>
    </div>

    <div id="grupoFisica">

        <div class="form-group">
            <b>@Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @id = "CPF", @class = "form-control", @data_val = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @id = "DataNascimento", @class = "form-control", @data_val = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @id = "Nome", @class = "form-control", @data_val = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @id = "Sobrenome", @class = "form-control", @data_val = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <div id="grupoJuridica">
        <div class="form-group">
            <b>@Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @id = "CNPJ", @class = "form-control", @data_val = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.CNPJ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazaoSocial, new { htmlAttributes = new { @id = "RazaoSocial", @class = "form-control", @data_val = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.RazaoSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.NomeFantasia, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeFantasia, new { htmlAttributes = new { @id = "NomeFantasia", @class = "form-control", @data_val = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.NomeFantasia, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @id = "CEP", @class = "form-control", @data_val = "true", @required = "required" } })
            @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Logradouro, new { htmlAttributes = new { @id = "Logradouro", @class = "form-control", @data_val = "true", @required = "required", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Logradouro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @id = "Numero", @class = "form-control", @data_val = "true", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Completemento, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Completemento, new { htmlAttributes = new { @id = "Completemento", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Completemento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @id = "Bairro", @class = "form-control", @data_val = "true", @required = "required", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @id = "Cidade", @class = "form-control", @data_val = "true", @required = "required", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @id = "UF", @class = "form-control", @data_val = "true", @required = "required", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
    </div>

</div>

}

<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>

Views/Pessoa/Delete.cshtml
@model cadastro_cliente_mvc.Models.Pessoa
@{
    ViewData["Title"] = "Deletar Pessoa";
}

<h2>Deletar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.HiddenFor(model => model.pessoaId)

    @if (Model.tipoPessoa == "F")
    {
        <h4>Pessoa Física</h4>
        <hr />
        <div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.CPF)
                </div>
            </div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Nome)
                </div>

            </div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Sobrenome)
                </div>
            </div>

            <div class="form-group">
                <b>@Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.DataNascimento)
                </div>
            </div>
        </div>
    }
    else
    {
        <h4>Pessoa Jurídica</h4>
        <hr />
        <div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.CNPJ)
                </div>
            </div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.RazaoSocial)
                </div>
            </div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.NomeFantasia, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.NomeFantasia)
                </div>
            </div>
        </div>
    }


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Deletar" class="btn btn-danger" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>

Views/Pessoa/Details.cshtml
@model cadastro_cliente_mvc.Models.Pessoa
@{
    ViewData["Title"] = "Datalhes Pessoa";
}

<h2>Datalhes</h2>

<div class="form-horizontal">

    @if (Model.tipoPessoa == "F")
    {
        <h4>Pessoa Física</h4>
        <hr />
        <div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.CPF)
                </div>
            </div>
            <div class="form-group">

                <b>@Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Nome)
                </div>

            </div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Sobrenome)
                </div>
            </div>

            <div class="form-group">
                <b>@Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.DataNascimento)
                </div>
            </div>
        </div>
    }
    else
    {
        <h4>Pessoa Jurídica</h4>
        <hr />
        <div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.CNPJ)
                </div>
            </div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.RazaoSocial)
                </div>
            </div>
            <div class="form-group">
                <b>@Html.LabelFor(model => model.NomeFantasia, htmlAttributes: new { @class = "control-label col-md-2" })</b>
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.NomeFantasia)
                </div>
            </div>
        </div>
    }

    <div class="form-group">
        <b>@Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CEP)
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Logradouro)
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Numero)
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Completemento, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Completemento)
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Bairro)
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Cidade)
        </div>
    </div>

    <div class="form-group">
        <b>@Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col-md-2" })</b>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.UF)
        </div>
    </div>

</div>


<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>

Views/Pessoa/Index.cshtml
@model IEnumerable<cadastro_cliente_mvc.Models.Pessoa>
@{
    ViewData["Title"] = "Lista de Pessoas";
}

<h2>Lista de Pessoas</h2>
@Html.ActionLink("Adicionar", "Add")
<table class="table">
    <tr>
        <th>Id</th>
        <th>Tipo Pessoa</th>
        <th>CPF / CNPJ</th>
        <th>Nome / Razão Social</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.pessoaId)</td>

            @if (item.tipoPessoa == "F")
            {
                <td>
                    Física
                </td>
            }
            else
            {
                <td>
                    Jurídica
                </td>
            }

            <td>
                @if (item.tipoPessoa == "F")
                {
                    @Html.DisplayFor(modelItem => item.CPF)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.CNPJ)
                }
            </td>
            <td>
                @if (item.tipoPessoa == "F")
                {
                    @Html.DisplayFor(modelItem => item.Nome)
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.RazaoSocial)
                }
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.pessoaId }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.pessoaId }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.pessoaId })
            </td>
        </tr>
    }
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro de Cliente</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro de Cliente</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Principal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Cadastro de Pessoa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Cadastro de Cliente
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://rawgit.com/RobinHerbots/Inputmask/3.x/dist/jquery.inputmask.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/buscaCep.js" asp-append-version="true"></script>
    <script src="~/js/mask.js" asp-append-version="true"></script>
    <script src="~/js/tipoPessoa.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>